### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by LittleYang0531** [SonolusHaniwa/sonolus-server-cpp#9]
以下是预期的近期开发进程（依照实际开发情况，可能顺序会有所变动）：

- [x] 重新编写 Readme。简化 Readme 内容，并将部分内容移植到 Wiki 界面里。
- [x] 新增对 Sonolus 0.7.0 的支持，并自适应配置文件中的 `Sonolus.Version`。v1.4.2
- [x] 重写 libsonolusjs 和 libsonolush，更新 Plugin 版本号为 1.4.2。v1.4.2
- [x] 重新设计数据包格式，重写 export 功能。v1.4.3
- [x] 新增对官方资源包格式的支持。v1.4.3
- [x] 完善 export 功能: 新增临时文件用于重载下载进度。v1.4.4
- [x] 新增自定义翻译功能，新增对 localization 参数的支持。v1.4.4
- [x] 新增对各资源 Description 的支持。v1.4.4
- [x] 将 Sonolus App 自带的翻译环境变量添加进去。v1.4.4
- [x] 新增对 Sonolus 0.7.2 的支持。v1.4.5
- [x] 新增对 Sonolus 0.7.3 的支持。v1.4.6
- [x] 新增 cgi 功能，以支持搭建至 Vercel 等无服务器平台。v1.4.7
- [ ] 新增对多服务器的支持。v1.5.0
- [ ] 重新设计 UI，新增主题功能，支持用户自定义主题。v1.5.1
- [ ] 新增 Android 端应用。v1.6.0
